name: scheduling_management_app
description: "A new Flutter project."
publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  path: ^1.9.1
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  local_auth: ^2.3.0
  dartz: ^0.10.1
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  rxdart: ^0.28.0
  permission_handler: ^12.0.0+1
  device_info_plus: ^9.1.2
  open_file: ^3.3.2
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.0.0
  table_calendar: ^3.0.8
  firebase_core: ^4.1.1
  provider: ^6.1.5+1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  google_sign_in: ^7.2.0
  cloud_functions: ^6.0.2
  firebase_storage: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # - .env.v2
    - assets/schedulo_logo.png
    - assets/fonts/Oswald-Bold.ttf
    - assets/fonts/Oswald-Regular.ttf
    - assets/fonts/Oswald-Light.ttf
    - assets/fonts/Oswald-VariableFont_wght.ttf

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  linux: true
  windows:
    generate: true
    image_path: "assets/schedulo_logo.png"
  web:
    generate: true
    image_path: "assets/schedulo_logo.png"
    background_color: "#FB707E"
    theme_color: "#FB707E"
  image_path: "assets/schedulo_logo.png"
  adaptive_icon_background: "#FB707E"
  adaptive_icon_foreground: "assets/schedulo_logo.png"
