name: scheduling_management_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  supabase_flutter: ^2.8.4
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  path: ^1.9.1
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  local_auth: ^2.3.0
  dartz: ^0.10.1
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/schedule_app_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  linux: true
  windows:
    generate: true
    image_path: "assets/images/schedule_app_logo.png"
  web:
    generate: true
    image_path: "assets/images/schedule_app_logo.png"
    background_color: "#3366C2"
    theme_color: "#3366C2"
  image_path: "assets/images/schedule_app_logo.png"
  adaptive_icon_background: "#3366C2"
  adaptive_icon_foreground: "assets/images/schedule_app_logo.png"
